apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: k6wvwyrzi-go 
  janus-idp.io/tekton: k6wvwyrzi-go
  backstage.io/kubernetes-id: k6wvwyrzi-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: k6wvwyrzi-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  