apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: k6wvwyrzi-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: k6wvwyrzi-go 
  name: k6wvwyrzi-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: k6wvwyrzi-go 
